### ISSUE TITLE
Add Minimum quantity data in the inventory list

### ISSUE THREAD

**Issue by rithviknishad** [ohcnetwork/care#1721]
Ref: https://github.com/coronasafe/care_fe/issues/6612

**Comment by vasudevravula** [comment]
@rithviknishad I see this error when I do docker compose and unable to run the app locally, can you help me with this?

[+] Building 0.0s (0/0)                                                                                  docker:default
[+] Running 7/6
 ✔ Network care                 Created                                                                            0.1s
 ✔ Container care-fidelius-1    Created                                                                            0.1s
 ✔ Container care-redis-1       Created                                                                            0.1s
 ✔ Container care-localstack-1  Created                                                                            0.2s
 ✔ Container care-db-1          Created                                                                            0.1s
 ✔ Container care-backend-1     Created                                                                            0.2s
 ✔ Container care-celery-1      Created                                                                            0.1s
Attaching to care-backend-1, care-celery-1, care-db-1, care-fidelius-1, care-localstack-1, care-redis-1
care-redis-1       | 1:C 06 Dec 2023 03:53:38.917 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
care-redis-1       | 1:C 06 Dec 2023 03:53:38.918 * oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
care-redis-1       | 1:C 06 Dec 2023 03:53:38.918 * Redis version=7.2.3, bits=64, commit=00000000, modified=0, pid=1, just started
care-redis-1       | 1:C 06 Dec 2023 03:53:38.918 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
care-redis-1       | 1:M 06 Dec 2023 03:53:38.918 * monotonic clock: POSIX clock_gettime
care-redis-1       | 1:M 06 Dec 2023 03:53:38.919 * Running mode=standalone, port=6379.
care-redis-1       | 1:M 06 Dec 2023 03:53:38.919 * Server initialized
care-redis-1       | 1:M 06 Dec 2023 03:53:38.919 * Loading RDB produced by version 7.2.3
care-redis-1       | 1:M 06 Dec 2023 03:53:38.919 * RDB age 89 seconds
care-redis-1       | 1:M 06 Dec 2023 03:53:38.919 * RDB memory usage when created 0.83 Mb
care-redis-1       | 1:M 06 Dec 2023 03:53:38.919 * Done loading RDB, keys loaded: 0, keys expired: 0.
care-redis-1       | 1:M 06 Dec 2023 03:53:38.919 * DB loaded from disk: 0.000 seconds
care-redis-1       | 1:M 06 Dec 2023 03:53:38.919 * Ready to accept connections tcp
care-db-1          |
care-db-1          | PostgreSQL Database directory appears to contain a database; Skipping initialization
care-db-1          |
care-db-1          | 2023-12-06 03:53:39.952 UTC [1] LOG:  starting PostgreSQL 16.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924, 64-bit
care-db-1          | 2023-12-06 03:53:39.953 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
care-db-1          | 2023-12-06 03:53:39.953 UTC [1] LOG:  listening on IPv6 address "::", port 5432
care-db-1          | 2023-12-06 03:53:40.016 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
care-db-1          | 2023-12-06 03:53:40.086 UTC [24] LOG:  database system was shut down at 2023-12-06 03:52:09 UTC
care-db-1          | 2023-12-06 03:53:40.116 UTC [1] LOG:  database system is ready to accept connections
care-localstack-1  | ERROR: 'rm -rf "/tmp/localstack"': exit code 1; output: b"rm: cannot remove '/tmp/localstack': Device or resource busy\n"
care-localstack-1  | Traceback (most recent call last):
care-localstack-1  |   File "<frozen runpy>", line 198, in _run_module_as_main
care-localstack-1  |   File "<frozen runpy>", line 88, in _run_code
care-localstack-1  |   File "/opt/code/localstack/localstack/runtime/main.py", line 28, in <module>
care-localstack-1  |     main()
care-localstack-1  |   File "/opt/code/localstack/localstack/runtime/main.py", line 20, in main
care-localstack-1  |     infra.start_infra(asynchronous=False)
care-localstack-1  |   File "/opt/code/localstack/localstack/services/infra.py", line 235, in start_infra
care-localstack-1  |     files.rm_rf(config.dirs.tmp)
care-localstack-1  |   File "/opt/code/localstack/localstack/utils/files.py", line 214, in rm_rf
care-localstack-1  |     shutil.rmtree(path)
care-localstack-1  |   File "/usr/local/lib/python3.11/shutil.py", line 738, in rmtree
care-localstack-1  |     onerror(os.rmdir, path, sys.exc_info())
care-localstack-1  |   File "/usr/local/lib/python3.11/shutil.py", line 736, in rmtree
care-localstack-1  |     os.rmdir(path, dir_fd=dir_fd)
care-localstack-1  | OSError: [Errno 16] Device or resource busy: '/tmp/localstack'
: invalid option namescripts/start-dev.sh: line 2: set: pipefail
care-backend-1 exited with code 2
care-localstack-1 exited with code 1
care-celery-1      | scripts/celery-dev.sh: line 2: $'\r': command not found
care-fidelius-1    |
care-fidelius-1    |   .   ____          _            __ _ _
care-fidelius-1    |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
care-fidelius-1    | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
care-fidelius-1    |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
care-fidelius-1    |   '  |____| .__|_| |_|_| |_\__, | / / / /
care-fidelius-1    |  =========|_|==============|___/=/_/_/_/
care-fidelius-1    |  :: Spring Boot ::                (v2.4.3)
care-fidelius-1    |
care-celery-1      | usage: watchmedo [-h] [--version]
care-celery-1      |                  {tricks-from,tricks,tricks-generate-yaml,generate-tricks-yaml,log,shell-command,auto-restart}
care-celery-1      |                  ...
care-celery-1      | watchmedo: error: argument top_command: invalid choice: '\r' (choose from 'tricks-from', 'tricks', 'tricks-generate-yaml', 'generate-tricks-yaml', 'log', 'shell-command', 'auto-restart')
care-celery-1      | scripts/celery-dev.sh: line 4: auto-restart: command not found
care-fidelius-1    | 2023-12-06 03:53:42.543  INFO 1 --- [           main] i.p.fidelius.FideliusApplication         : Starting FideliusApplication using Java 11.0.19 on e0f189000321 with PID 1 (/app/spring-boot-application.jar started by root in /)
care-fidelius-1    | 2023-12-06 03:53:42.553  INFO 1 --- [           main] i.p.fidelius.FideliusApplication         : No active profile set, falling back to default profiles: default
care-celery-1      | Usage: celery worker [OPTIONS]
care-celery-1      | Try 'celery worker --help' for help.
care-celery-1      |
care-celery-1      | Error: Invalid value for '-l' / '--loglevel': 'INFO\r' is not one of 'DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', 'FATAL'.
care-celery-1 exited with code 2
care-fidelius-1    | 2023-12-06 03:53:44.302  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8090 (http)
care-fidelius-1    | 2023-12-06 03:53:44.329  INFO 1 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
care-fidelius-1    | 2023-12-06 03:53:44.330  INFO 1 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.43]
care-fidelius-1    | 2023-12-06 03:53:44.446  INFO 1 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
care-fidelius-1    | 2023-12-06 03:53:44.446  INFO 1 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1675 ms
care-fidelius-1    | 2023-12-06 03:53:44.769  INFO 1 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
care-fidelius-1    | 2023-12-06 03:53:45.034  INFO 1 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8090 (http) with context path ''
care-fidelius-1    | 2023-12-06 03:53:45.053  INFO 1 --- [           main] i.p.fidelius.FideliusApplication         : Started FideliusApplication in 3.846 seconds (JVM running for 5.471)
care-fidelius-1    | 2023-12-06 03:57:56.987  INFO 1 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'

**Comment by rithviknishad** [comment]
What's the command you've used to compose this up? (Refer: https://github.com/coronasafe/care?tab=readme-ov-file#compose)

**Comment by vasudevravula** [comment]
> What's the command you've used to compose this up? (Refer: https://github.com/coronasafe/care?tab=readme-ov-file#compose)

I've used make up

**Comment by vasudevravula** [comment]
@rithviknishad I followed the instructions on the readme, will you be able to help me with this?

**Comment by rithviknishad** [comment]
Are you on windows?

**Comment by rithviknishad** [comment]
@vasudevravula 

<img width="869" alt="image" src="https://github.com/coronasafe/care/assets/25143503/5e0a6592-ebd2-4f73-b107-e148558b225d">

(from the README btw)

**Comment by vasudevravula** [comment]
@rithviknishad yeah, I did this and before posting here

**Comment by vasudevravula** [comment]
@rithviknishad I got this working, I had to change the localstack and fidelius images to arm images

**Comment by vasudevravula** [comment]
@rithviknishad created this PR, can you please take a look [1763](https://github.com/coronasafe/care/pull/1763)
